login_project/login_app/urls.py
from django.conf.urls import url
from login_app import views

app_name = 'login_app'

urlpatterns = [
    url(r'^register',views.register,name='register'),
    url(r'^user_login/$',views.user_login,name='user_login'),
]

login_project/login_project/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from login_app import views

urlpatterns = [
    url(r'^$',views.index,name='index'),
    path('admin/', admin.site.urls),
    url(r'^login_app/',include('login_app.urls')),
    url(r'^logout/$',views.user_logout,name='logout'),
    url(r'^special/$',views.special,name='special'),
]

login_project/login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)

    # additional fields
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

login_project/login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username','email','password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

login_project/login_app/views.py
from django.shortcuts import render
from login_app.forms import UserForm,UserProfileInfoForm
from login_app.models import UserProfileInfo
# Create your views here.

#
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.urls import reverse
from django.contrib.auth.decorators import login_required


def index(request):
    return render(request,'login_app/index.html')

@login_required
def special(request):
    return HttpResponse("You are logged in!")

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):
    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic=request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors,profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    return render(request,'login_app/registration.html',{'user_form':user_form,
                                                'profile_form':profile_form,
                                                'registered':registered})



def user_login(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        print("User tried with usrname : {}" .format(username))
        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))

            else:
                return HttpResponse("User is not active")

        else:
            print("Unauthenticated user tried to login and failed")
            print("User name : {} and Password : {}".format(username,password))

            return HttpResponse("Invalid credentials, check your username and password")
    else:
        return render(request,'login_app/login.html',{})

login_project/templates/login_app/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous"> -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  </head>
  <body>

    <!-- <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <ul class="nav navbar-nav">

          <li><a class="navbar-brand " href="{% url 'index' %}">Brand</a></li>
          <li><a class="navbar-link" href="{% url 'index' %}">Home</a></li>
          <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
          <li><a class="navbar-link" href="{% url 'login_app:register' %}">Register</a></li>

          {% if user.is_authenticated %}
            <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
          {% else %}
            <li><a class="navbar-link" href="{% url 'login_app:user_login' %}">Login  </a></li>
          {% endif %}
        </ul>
      </div>
    </nav>
    -->



  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Brand</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'login_app:register' %}">Register</a>
      </li>

      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login_app:user_login' %}">Login</a>
        </li>
      {% endif %}

    </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>
      <div class="container">
          {% block body_block %}

          {% endblock %}
      </div>

  </body>
</html>

login_project/templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block body_block %}
  <div class="jumbotron">
    <h2>Welcome to Djago level five</h2>
    <h2>Its a index page</h2>
  </div>
{% endblock %}

login_project/templates/login_app/login.html
{% extends "login_app/base.html" %}

{% block body_block %}
  <div class="jumbotron">
    <h2>Login in here</h2>
    <form action="{% url 'login_app:user_login' %}" method="post">
      {% csrf_token %}
      <label for="username">Username:</label>
      <input type="text" name="username" placeholder="enter username">

      <label for="password">Password:</label>
      <input type="password" name="password">

      <input type="submit" name="" value="Login">
    </form>
  </div>
{% endblock %}

login_project/templates/login_app/registration.html
{% extends "login_app/base.html" %}
{% load static %}

{% block body_block %}
  <div class="jumbotron">
      {% if registered %}
        <h2>Thank you for registering!</h2>
      {% else %}
        <h2>Register here</h2>
        <h3>Fill out the below form</h3>

        <form enctype="multipart/form-data" method="post">
          {% csrf_token %}
          {{ user_form.as_p }}
          {{ profile_form.as_p }}

          <input type="submit" class="btn btn-primary" value="Register">
        </form>
      {% endif %}
  </div>
{% endblock %}